# Problem 1: Add two randomly generated NumPy 3D-matrices(tensor) using loops
HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]

In [1]:
import numpy as np

In [259]:
Matrix1 = np.random.rand(2, 2, 2)
print(Matrix1)
print(Matrix1.shape)

[[[0.61354778 0.36063423]
  [0.56198369 0.54985153]]

 [[0.50645713 0.51452888]
  [0.91821944 0.53156387]]]
(2, 2, 2)


In [274]:
Matrix2 = np.random.rand(2, 2, 2)
print(Matrix2)
print(Matrix2.shape)

[[[0.39134226 0.55061415]
  [0.93159731 0.54159685]]

 [[0.8324457  0.06495119]
  [0.7322383  0.39500773]]]
(2, 2, 2)


In [275]:
Result = Matrix1 + Matrix2
print(Result)
print(Result.shape)

[[[1.00489004 0.91124837]
  [1.493581   1.09144838]]

 [[1.33890283 0.57948008]
  [1.65045775 0.9265716 ]]]
(2, 2, 2)


In [276]:
(r, c, b) = Result.shape
print(r, c, b)
Result1 = np.zeros((r, c, b))
print(Result1)

2 2 2
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [279]:
for i in range(len(Matrix1)):
    for j in range(len(Matrix1)):
        for k in range(len(Matrix1)):
            Result1[i][j][k] = Matrix1[i][j][k] + Matrix2[i][j][k]

print(Result1)

[[[1.00489004 0.91124837]
  [1.493581   1.09144838]]

 [[1.33890283 0.57948008]
  [1.65045775 0.9265716 ]]]


# Problem 2: Find if a point is inside or outside a rectangle.
HINT: How do you represent a rectangle?

In [20]:
x1 = int(input("Enter 1st co-ordinate of diagonal of rectangle:"))
y1 = int(input("Enter 2nd co-ordinate of diagonal of rectangle:"))
x3 = int(input("Enter 5th co-ordinate of diagonal of rectangle:"))
y3 = int(input("Enter 6th co-ordinate of diagonal of rectangle:"))
print(x1, y1, x3, y3)

Enter 1st co-ordinate of diagonal of rectangle:10
Enter 2nd co-ordinate of diagonal of rectangle:10
Enter 5th co-ordinate of diagonal of rectangle:-20
Enter 6th co-ordinate of diagonal of rectangle:-20
10 10 -20 -20


In [23]:
x = int(input("Enter X co-ordinate of Point:"))
y = int(input("Enter Y co-ordinate of a point:"))
print(x, y)

Enter X co-ordinate of Point:20
Enter Y co-ordinate of a point:-20
20 -20


In [24]:
if x < x1 and x > x3 and y < y1 and y > y3:
    print("Poitn is Inside the Rectangle")
else:
    print("Point is Outside the Rectangle")

Point is Outside the Rectangle


# Problem 3: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [25]:
Matrix = np.random.rand(4, 5, 6)
print(Matrix)

[[[0.31514312 0.66860004 0.56265157 0.30893959 0.0256028  0.99315313]
  [0.93698918 0.24868672 0.19983323 0.87731289 0.53314881 0.62037741]
  [0.1558371  0.69724956 0.06373    0.15437051 0.00829758 0.17183296]
  [0.36983997 0.35982959 0.09171483 0.85541122 0.46820873 0.32682453]
  [0.82709283 0.77492372 0.36785405 0.6285336  0.7036287  0.18392702]]

 [[0.3394986  0.4303748  0.54828225 0.50201482 0.0255318  0.83494747]
  [0.82151522 0.92808822 0.80970458 0.05631703 0.99930439 0.43522789]
  [0.76840121 0.37626537 0.58309627 0.70243939 0.53053997 0.53138936]
  [0.34230723 0.37151457 0.09357106 0.00271411 0.84926899 0.3351942 ]
  [0.68553357 0.06269005 0.01536136 0.89771964 0.16971394 0.87280078]]

 [[0.04297108 0.56895298 0.03697455 0.24477882 0.75645176 0.00973751]
  [0.05563463 0.5905078  0.19649644 0.53340089 0.84000129 0.87697307]
  [0.45301275 0.3540494  0.76127135 0.13422885 0.81492661 0.13326012]
  [0.97579145 0.80146019 0.78778486 0.04164816 0.68907545 0.77855361]
  [0.50118604 0.

In [29]:
print( np.reshape(Matrix, 120, 'C'))

[0.31514312 0.66860004 0.56265157 0.30893959 0.0256028  0.99315313
 0.93698918 0.24868672 0.19983323 0.87731289 0.53314881 0.62037741
 0.1558371  0.69724956 0.06373    0.15437051 0.00829758 0.17183296
 0.36983997 0.35982959 0.09171483 0.85541122 0.46820873 0.32682453
 0.82709283 0.77492372 0.36785405 0.6285336  0.7036287  0.18392702
 0.3394986  0.4303748  0.54828225 0.50201482 0.0255318  0.83494747
 0.82151522 0.92808822 0.80970458 0.05631703 0.99930439 0.43522789
 0.76840121 0.37626537 0.58309627 0.70243939 0.53053997 0.53138936
 0.34230723 0.37151457 0.09357106 0.00271411 0.84926899 0.3351942
 0.68553357 0.06269005 0.01536136 0.89771964 0.16971394 0.87280078
 0.04297108 0.56895298 0.03697455 0.24477882 0.75645176 0.00973751
 0.05563463 0.5905078  0.19649644 0.53340089 0.84000129 0.87697307
 0.45301275 0.3540494  0.76127135 0.13422885 0.81492661 0.13326012
 0.97579145 0.80146019 0.78778486 0.04164816 0.68907545 0.77855361
 0.50118604 0.56035373 0.08256386 0.25802323 0.24607536 0.36744

In [30]:
print( np.reshape(Matrix, 120, 'F'))

[0.31514312 0.3394986  0.04297108 0.86683113 0.93698918 0.82151522
 0.05563463 0.58908533 0.1558371  0.76840121 0.45301275 0.94353742
 0.36983997 0.34230723 0.97579145 0.17240565 0.82709283 0.68553357
 0.50118604 0.6529992  0.66860004 0.4303748  0.56895298 0.36962869
 0.24868672 0.92808822 0.5905078  0.7845864  0.69724956 0.37626537
 0.3540494  0.66374867 0.35982959 0.37151457 0.80146019 0.73920221
 0.77492372 0.06269005 0.56035373 0.15946299 0.56265157 0.54828225
 0.03697455 0.36911459 0.19983323 0.80970458 0.19649644 0.32540502
 0.06373    0.58309627 0.76127135 0.66316711 0.09171483 0.09357106
 0.78778486 0.10112382 0.36785405 0.01536136 0.08256386 0.38134941
 0.30893959 0.50201482 0.24477882 0.86352906 0.87731289 0.05631703
 0.53340089 0.42252436 0.15437051 0.70243939 0.13422885 0.979642
 0.85541122 0.00271411 0.04164816 0.33116625 0.6285336  0.89771964
 0.25802323 0.21100202 0.0256028  0.0255318  0.75645176 0.16062219
 0.53314881 0.99930439 0.84000129 0.83863472 0.00829758 0.530539

In [33]:
print( np.reshape(Matrix, (10, 12), 'C'))

[[0.31514312 0.66860004 0.56265157 0.30893959 0.0256028  0.99315313
  0.93698918 0.24868672 0.19983323 0.87731289 0.53314881 0.62037741]
 [0.1558371  0.69724956 0.06373    0.15437051 0.00829758 0.17183296
  0.36983997 0.35982959 0.09171483 0.85541122 0.46820873 0.32682453]
 [0.82709283 0.77492372 0.36785405 0.6285336  0.7036287  0.18392702
  0.3394986  0.4303748  0.54828225 0.50201482 0.0255318  0.83494747]
 [0.82151522 0.92808822 0.80970458 0.05631703 0.99930439 0.43522789
  0.76840121 0.37626537 0.58309627 0.70243939 0.53053997 0.53138936]
 [0.34230723 0.37151457 0.09357106 0.00271411 0.84926899 0.3351942
  0.68553357 0.06269005 0.01536136 0.89771964 0.16971394 0.87280078]
 [0.04297108 0.56895298 0.03697455 0.24477882 0.75645176 0.00973751
  0.05563463 0.5905078  0.19649644 0.53340089 0.84000129 0.87697307]
 [0.45301275 0.3540494  0.76127135 0.13422885 0.81492661 0.13326012
  0.97579145 0.80146019 0.78778486 0.04164816 0.68907545 0.77855361]
 [0.50118604 0.56035373 0.08256386 0.25802

In [34]:
print( np.reshape(Matrix, (10, 12), 'F'))

[[0.31514312 0.45301275 0.66860004 0.3540494  0.56265157 0.76127135
  0.30893959 0.13422885 0.0256028  0.81492661 0.99315313 0.13326012]
 [0.3394986  0.94353742 0.4303748  0.66374867 0.54828225 0.66316711
  0.50201482 0.979642   0.0255318  0.06448346 0.83494747 0.80375168]
 [0.04297108 0.36983997 0.56895298 0.35982959 0.03697455 0.09171483
  0.24477882 0.85541122 0.75645176 0.46820873 0.00973751 0.32682453]
 [0.86683113 0.34230723 0.36962869 0.37151457 0.36911459 0.09357106
  0.86352906 0.00271411 0.16062219 0.84926899 0.44094432 0.3351942 ]
 [0.93698918 0.97579145 0.24868672 0.80146019 0.19983323 0.78778486
  0.87731289 0.04164816 0.53314881 0.68907545 0.62037741 0.77855361]
 [0.82151522 0.17240565 0.92808822 0.73920221 0.80970458 0.10112382
  0.05631703 0.33116625 0.99930439 0.30101208 0.43522789 0.17106587]
 [0.05563463 0.82709283 0.5905078  0.77492372 0.19649644 0.36785405
  0.53340089 0.6285336  0.84000129 0.7036287  0.87697307 0.18392702]
 [0.58908533 0.68553357 0.7845864  0.0626

In [35]:
print( np.reshape(Matrix, (10, -2), 'C'))

[[0.31514312 0.66860004 0.56265157 0.30893959 0.0256028  0.99315313
  0.93698918 0.24868672 0.19983323 0.87731289 0.53314881 0.62037741]
 [0.1558371  0.69724956 0.06373    0.15437051 0.00829758 0.17183296
  0.36983997 0.35982959 0.09171483 0.85541122 0.46820873 0.32682453]
 [0.82709283 0.77492372 0.36785405 0.6285336  0.7036287  0.18392702
  0.3394986  0.4303748  0.54828225 0.50201482 0.0255318  0.83494747]
 [0.82151522 0.92808822 0.80970458 0.05631703 0.99930439 0.43522789
  0.76840121 0.37626537 0.58309627 0.70243939 0.53053997 0.53138936]
 [0.34230723 0.37151457 0.09357106 0.00271411 0.84926899 0.3351942
  0.68553357 0.06269005 0.01536136 0.89771964 0.16971394 0.87280078]
 [0.04297108 0.56895298 0.03697455 0.24477882 0.75645176 0.00973751
  0.05563463 0.5905078  0.19649644 0.53340089 0.84000129 0.87697307]
 [0.45301275 0.3540494  0.76127135 0.13422885 0.81492661 0.13326012
  0.97579145 0.80146019 0.78778486 0.04164816 0.68907545 0.77855361]
 [0.50118604 0.56035373 0.08256386 0.25802

In [36]:
print( np.reshape(Matrix, (-2, 12), 'F'))

[[0.31514312 0.45301275 0.66860004 0.3540494  0.56265157 0.76127135
  0.30893959 0.13422885 0.0256028  0.81492661 0.99315313 0.13326012]
 [0.3394986  0.94353742 0.4303748  0.66374867 0.54828225 0.66316711
  0.50201482 0.979642   0.0255318  0.06448346 0.83494747 0.80375168]
 [0.04297108 0.36983997 0.56895298 0.35982959 0.03697455 0.09171483
  0.24477882 0.85541122 0.75645176 0.46820873 0.00973751 0.32682453]
 [0.86683113 0.34230723 0.36962869 0.37151457 0.36911459 0.09357106
  0.86352906 0.00271411 0.16062219 0.84926899 0.44094432 0.3351942 ]
 [0.93698918 0.97579145 0.24868672 0.80146019 0.19983323 0.78778486
  0.87731289 0.04164816 0.53314881 0.68907545 0.62037741 0.77855361]
 [0.82151522 0.17240565 0.92808822 0.73920221 0.80970458 0.10112382
  0.05631703 0.33116625 0.99930439 0.30101208 0.43522789 0.17106587]
 [0.05563463 0.82709283 0.5905078  0.77492372 0.19649644 0.36785405
  0.53340089 0.6285336  0.84000129 0.7036287  0.87697307 0.18392702]
 [0.58908533 0.68553357 0.7845864  0.0626

# Problem 4: Achieve the Array transformer using numpy.concatenate

In [37]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)

[[7.10108983e-01 1.44855633e-01 7.02659309e-01 6.76757303e-01]
 [7.70696684e-01 9.80102281e-01 8.13649670e-01 5.04670884e-01]
 [7.13286391e-01 3.20248969e-01 4.66460174e-01 9.82658801e-01]
 [5.64181865e-01 8.30784872e-01 4.72914233e-01 8.27186673e-01]
 [9.18900226e-04 8.71053721e-01 2.06198392e-01 6.77702767e-01]]
[[0.83893104 0.9549786 ]
 [0.13841271 0.37457758]
 [0.0414071  0.95097035]
 [0.20504022 0.02377195]
 [0.33773781 0.68652232]]


In [43]:
C = np.concatenate((A, B), axis = 1)
print(C)

[[7.10108983e-01 1.44855633e-01 7.02659309e-01 6.76757303e-01
  8.38931041e-01 9.54978595e-01]
 [7.70696684e-01 9.80102281e-01 8.13649670e-01 5.04670884e-01
  1.38412707e-01 3.74577579e-01]
 [7.13286391e-01 3.20248969e-01 4.66460174e-01 9.82658801e-01
  4.14071016e-02 9.50970355e-01]
 [5.64181865e-01 8.30784872e-01 4.72914233e-01 8.27186673e-01
  2.05040218e-01 2.37719461e-02]
 [9.18900226e-04 8.71053721e-01 2.06198392e-01 6.77702767e-01
  3.37737809e-01 6.86522323e-01]]


In [45]:
D = np.random.rand(5,4);
print(D);

E = np.random.rand(4,4);
print(E)

[[0.95556111 0.07561373 0.68883565 0.5164626 ]
 [0.47731283 0.53598196 0.91220942 0.43097393]
 [0.02527996 0.73472982 0.46628959 0.12256015]
 [0.26042512 0.60103089 0.23254357 0.07313227]
 [0.52682312 0.91135577 0.97481836 0.26665592]]
[[0.55062782 0.65523542 0.60744782 0.09905464]
 [0.62378301 0.23827312 0.21345541 0.62917964]
 [0.68361348 0.75274268 0.23753835 0.32481046]
 [0.78113691 0.85438425 0.63630084 0.75155732]]


In [46]:
F = np.concatenate((D, E), axis = 0)
print(F)

[[0.95556111 0.07561373 0.68883565 0.5164626 ]
 [0.47731283 0.53598196 0.91220942 0.43097393]
 [0.02527996 0.73472982 0.46628959 0.12256015]
 [0.26042512 0.60103089 0.23254357 0.07313227]
 [0.52682312 0.91135577 0.97481836 0.26665592]
 [0.55062782 0.65523542 0.60744782 0.09905464]
 [0.62378301 0.23827312 0.21345541 0.62917964]
 [0.68361348 0.75274268 0.23753835 0.32481046]
 [0.78113691 0.85438425 0.63630084 0.75155732]]


In [50]:
G = np.random.rand(5,4,3)
print(G.shape);

H = np.random.rand(5,3,3)
print(H.shape)

I = np.concatenate((G, H), axis = 1)
print(I.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)
